# Generated by Django 5.2.4 on 2025-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexport', '0002_finalreport_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='docraptor_status_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
