# Generated by Django 5.2.4 on 2025-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfexport', '0003_finalreport_docraptor_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
