# Generated by Django 5.2.4 on 2025-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentparticipant',
            name='last_invited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
