# Generated by Django 5.2.4 on 2025-07-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(3, 'Consistently true'), (2, 'Somewhat true'), (1, 'Somewhat untrue'), (0, 'Consistently untrue')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teams.teammember')),
            ],
            options={
                'unique_together': {('team_member', 'question')},
            },
        ),
    ]
