# Generated by Django 5.2.4 on 2025-09-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentparticipant_last_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
