# Generated by Django 5.2.4 on 2025-07-12 04:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentparticipant_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentparticipant',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
