# Generated by Django 5.2.4 on 2025-09-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redemption",
            name="promocode",
        ),
        migrations.RemoveField(
            model_name="redemption",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="redemption",
            name="user",
        ),

        migrations.DeleteModel(
            name="Redemption",
        ),
        migrations.DeleteModel(
            name="PromoCode",
        ),
    ]
