# Generated by Django 5.2.4 on 2025-07-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='unique_token',
        ),
    ]
