# Generated by Django 5.2.4 on 2025-07-15 16:31

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniformRangeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, unique=True)),
                ('summary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PeakActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('range_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('action_text', markdownx.models.MarkdownxField()),
            ],
            options={
                'unique_together': {('peak', 'range_label')},
            },
        ),
        migrations.CreateModel(
            name='PeakInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('range_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('insight_text', markdownx.models.MarkdownxField()),
            ],
            options={
                'unique_together': {('peak', 'range_label')},
            },
        ),
        migrations.CreateModel(
            name='ResultsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('low_peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('summary_text', models.TextField()),
            ],
            options={
                'unique_together': {('high_peak', 'low_peak')},
            },
        ),
    ]
