# Generated by Django 5.2.4 on 2025-07-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_alter_assessmentparticipant_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2, unique=True)),
                ('action_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PeakInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2, unique=True)),
                ('insight_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniformRangeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, unique=True)),
                ('summary_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PeakRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_threshold', models.PositiveIntegerField()),
                ('medium_threshold', models.PositiveIntegerField()),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.peak')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('low_peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('summary_text', models.TextField()),
            ],
            options={
                'unique_together': {('high_peak', 'low_peak')},
            },
        ),
    ]
