# Generated by Django 5.2.4 on 2025-07-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeakRange',
        ),
    ]
