# Generated by Django 5.2.4 on 2025-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_peakactions_delete_peakaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(choices=[('CC', 'Collaborative Culture'), ('LA', 'Leadership Accountability'), ('SM', 'Strategic Momentum'), ('TM', 'Talent Magnetism')], max_length=2)),
                ('range_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('insight_text', models.TextField()),
            ],
            options={
                'unique_together': {('peak', 'range_label')},
            },
        ),
        migrations.DeleteModel(
            name='PeakInsight',
        ),
        migrations.AlterUniqueTogether(
            name='peakactions',
            unique_together={('peak', 'range_label')},
        ),
    ]
