# Generated by Django 5.2.4 on 2025-07-14 16:19

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_peakinsights_delete_peakinsight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakactions',
            name='action_text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='peakinsights',
            name='insight_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
